version = 0.1

[default]
[default.global.parameters]
stack_name = "pashto-dictionary"

[default.build.parameters]
cached   = true
parallel = true

[default.deploy.parameters]
capabilities      = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3        = false
s3_bucket         = "pashto-dictionary-sam-artifacts"
region            = "ap-southeast-1"
