import { Router } from 'express';
import { body, param, query } from 'express-validator';
import { verifyToken } from '../middleware/auth';
import { requireRole } from '../middleware/requireRole';
import {
  listActiveFields,
  listAllFields,
  createField,
  updateField,
  reorderFields,
  setFieldActive,
  addOption,
  renameOption,
  setOptionActive,
} from '../controllers/fieldController';
import { APPLIES_TO, FIELD_TYPES, MAX_FIELDS, MAX_OPTIONS } from '../utils/extraFields';
import { labelChain } from '../utils/lookups';

const router = Router();
const admin = [verifyToken, requireRole('admin')];

const appliesToMessage = `appliesTo must be one of: ${APPLIES_TO.join(', ')}`;
const idParam = param('id').isMongoId().withMessage('Invalid id');
const optionIdParam = param('optionId').isMongoId().withMessage('Invalid option id');

const listValidators = [query('appliesTo').optional().isIn(APPLIES_TO).withMessage(appliesToMessage)];

const createValidators = [
  body('appliesTo').isIn(APPLIES_TO).withMessage(appliesToMessage),
  body('type').isIn(FIELD_TYPES).withMessage(`type must be one of: ${FIELD_TYPES.join(', ')}`),
  labelChain('label'),
  body('required').optional().isBoolean({ strict: true }).withMessage('required must be true or false'),
  body('options').optional().isArray({ max: MAX_OPTIONS }).withMessage(`options must be an array of at most ${MAX_OPTIONS}`),
  labelChain('options.*.label'),
  body('key').not().exists().withMessage('key is generated by the server'),
];

const updateValidators = [
  idParam,
  ...['key', 'appliesTo', 'type', 'active', 'options'].map((f) =>
    body(f).not().exists().withMessage(`${f} cannot be changed here`)
  ),
  labelChain('label', true),
  body('required').optional().isBoolean({ strict: true }).withMessage('required must be true or false'),
  body('order').optional().isInt({ min: 0, max: 999 }).withMessage('order must be a whole number from 0 to 999').toInt(),
  body().custom((b) => ['label', 'required', 'order'].some((f) => b[f] !== undefined)).withMessage('Provide label, required or order'),
];

const reorderValidators = [
  body('appliesTo').isIn(APPLIES_TO).withMessage(appliesToMessage),
  body('ids').isArray({ min: 1, max: MAX_FIELDS }).withMessage('ids must be a non-empty array'),
  body('ids.*').isMongoId().withMessage('ids must be valid ids'),
];

const optionLabel = [idParam, labelChain('label')];

router.get('/', listValidators, listActiveFields);
router.get('/all', ...admin, listValidators, listAllFields);
router.post('/', ...admin, createValidators, createField);
router.put('/order', ...admin, reorderValidators, reorderFields);
router.patch('/:id', ...admin, updateValidators, updateField);
router.patch('/:id/deactivate', ...admin, idParam, setFieldActive(false));
router.patch('/:id/reactivate', ...admin, idParam, setFieldActive(true));
router.post('/:id/options', ...admin, optionLabel, addOption);
router.patch('/:id/options/:optionId', ...admin, optionIdParam, optionLabel, renameOption);
router.patch('/:id/options/:optionId/deactivate', ...admin, idParam, optionIdParam, setOptionActive(false));
router.patch('/:id/options/:optionId/reactivate', ...admin, idParam, optionIdParam, setOptionActive(true));

export = router;
